# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-02 15:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('countryId', models.IntegerField()),
                ('urlId', models.URLField()),
                ('feels', models.IntegerField()),
                ('length', models.IntegerField()),
            ],
        ),
    ]
