# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-12 16:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pfs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='country',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='id',
            field=models.IntegerField(auto_created=True, primary_key=True, serialize=False, unique=True),
        ),
    ]
