# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-12 17:03
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('pfs', '0003_remove_article_countryid'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='date',
            field=models.DateField(blank=True, default=datetime.datetime(2017, 5, 12, 17, 3, 42, 800848, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
