# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-20 13:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pfs', '0004_article_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.TextField(blank=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='article',
            name='country',
        ),
        migrations.AddField(
            model_name='country',
            name='article',
            field=models.ManyToManyField(to='pfs.Article'),
        ),
    ]
