# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-20 14:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pfs', '0005_auto_20170520_1520'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='country',
            name='article',
        ),
        migrations.AddField(
            model_name='country',
            name='article',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='pfs.Article'),
        ),
    ]
